import React, { useEffect } from "react";
import { Button } from "./Button";

const App: React.FC = () => {
  useEffect(() => {
    console.log("hydrated");
  }, []);
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
      </head>

      <body>
        <div>this is generated by react</div>
        <Button />
      </body>
    </html>
  );
};

export { App };
