import React, { useEffect, useState } from "react";
import { Button } from "./Button";

const App: React.FC = () => {
  const [hydrated, setHydrated] = useState(false);
  useEffect(() => {
    setHydrated(true);
    return () => {
      setHydrated(false);
    };
  }, []);

  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
      </head>

      <body>
        <div>this is generated by react</div>
        <Button />
        {hydrated && (
          <div>
            this page is hydrated, but this probably casuing hydration mismatch
          </div>
        )}
      </body>
    </html>
  );
};

export { App };
